version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - gocyclo
    - godot
    - govet
    - ineffassign
    - mnd
    - prealloc
    - revive
    - staticcheck
    - unparam
    - unused
  settings:
    gocyclo:
      min-complexity: 20
    mnd:
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
    revive:
      rules:
        - name: package-comments
          disabled: true
    testpackage:
      skip-regexp: .*
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
