// Code generated by introspect; DO NOT EDIT.

package schema

type ProductCreateInput struct {
	DescriptionHtml        *string                     `json:"descriptionHtml,omitempty"`
	Handle                 *string                     `json:"handle,omitempty"`
	Seo                    *SEOInput                   `json:"seo,omitempty"`
	ProductType            *string                     `json:"productType,omitempty"`
	Category               *string                     `json:"category,omitempty"`
	Tags                   []any                       `json:"tags"`
	TemplateSuffix         *string                     `json:"templateSuffix,omitempty"`
	GiftCardTemplateSuffix *string                     `json:"giftCardTemplateSuffix,omitempty"`
	Title                  *string                     `json:"title,omitempty"`
	Vendor                 *string                     `json:"vendor,omitempty"`
	GiftCard               *bool                       `json:"giftCard,omitempty"`
	CollectionsToJoin      []any                       `json:"collectionsToJoin"`
	CombinedListingRole    *CombinedListingsRole       `json:"combinedListingRole,omitempty"`
	Metafields             []any                       `json:"metafields"`
	ProductOptions         []any                       `json:"productOptions"`
	Status                 *ProductStatus              `json:"status,omitempty"`
	RequiresSellingPlan    *bool                       `json:"requiresSellingPlan,omitempty"`
	ClaimOwnership         *ProductClaimOwnershipInput `json:"claimOwnership,omitempty"`
}

type ProductUpdateInput struct {
	DescriptionHtml        *string        `json:"descriptionHtml,omitempty"`
	Handle                 *string        `json:"handle,omitempty"`
	Seo                    *SEOInput      `json:"seo,omitempty"`
	ProductType            *string        `json:"productType,omitempty"`
	Category               *string        `json:"category,omitempty"`
	Tags                   []any          `json:"tags"`
	TemplateSuffix         *string        `json:"templateSuffix,omitempty"`
	GiftCardTemplateSuffix *string        `json:"giftCardTemplateSuffix,omitempty"`
	Title                  *string        `json:"title,omitempty"`
	Vendor                 *string        `json:"vendor,omitempty"`
	RedirectNewHandle      *bool          `json:"redirectNewHandle,omitempty"`
	ID                     *string        `json:"id,omitempty"`
	CollectionsToJoin      []any          `json:"collectionsToJoin"`
	CollectionsToLeave     []any          `json:"collectionsToLeave"`
	Metafields             []any          `json:"metafields"`
	Status                 *ProductStatus `json:"status,omitempty"`
	RequiresSellingPlan    *bool          `json:"requiresSellingPlan,omitempty"`
}

type ProductClaimOwnershipInput struct {
	Bundles *bool `json:"bundles,omitempty"`
}

type SEOInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
}
